# Generated by Django 5.1.4 on 2025-01-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
